//go:build integration

package pgtest

import (
	"context"
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Tenant is one tenant's worth of seeded data: an organization, a member of its
// own, a project, a board, a column and a card.
//
// Every primary key is captured rather than generated by the database, because
// the isolation tests need to name the *other* tenant's rows by their real id.
// "Tenant A cannot list tenant B's cards" is a much weaker claim than "tenant A
// cannot read tenant B's card when it asks for it by primary key".
type Tenant struct {
	// Label distinguishes the two tenants in test output.
	Label string

	// TenantID is the organization id, which is also the value every
	// tenant-scoped row carries as tenant_id and the value that goes into
	// app.tenant_id.
	TenantID uuid.UUID

	// MemberID is the user who belongs to this tenant and no other.
	MemberID uuid.UUID

	// MembershipID joins MemberID to this tenant.
	MembershipID uuid.UUID

	// ProjectID, BoardID, ColumnID and CardID are one row per tenant-scoped
	// table in the domain hierarchy.
	ProjectID uuid.UUID
	BoardID   uuid.UUID
	ColumnID  uuid.UUID
	CardID    uuid.UUID

	// MemberEmail and CardTitle are the human-readable values assertions match
	// on.
	MemberEmail string
	CardTitle   string
}

// Fixture is two tenants and the user they have in common.
type Fixture struct {
	A Tenant
	B Tenant

	// SharedUserID belongs to both tenants. It is the reason this fixture
	// proves filtering rather than coincidence: without it, "tenant A sees only
	// its own members" would hold even if the query returned the entire users
	// table, because the two tenants' data would not overlap.
	SharedUserID uuid.UUID

	// SharedEmail identifies the shared user in assertions.
	SharedEmail string
}

// Tenants returns both tenants, for tests that assert something in each
// direction.
func (f Fixture) Tenants() []Tenant {
	return []Tenant{f.A, f.B}
}

// SeedTenants creates two independent tenants plus one user who belongs to
// both, and removes them when the test ends.
//
// It seeds through the superuser pool, because seeding is precisely what the
// policies forbid: no role subject to row-level security can create a user at
// all, since the users policy requires a membership that cannot exist before
// the user does. That is not a gap in the harness, it is issue #13 showing up
// exactly where migration 00002's header comment says it will.
//
// Since issue #14 that rules out the schema owner too, and deliberately: it is
// a non-superuser subject to FORCE ROW LEVEL SECURITY, so these inserts would
// be rejected and these deletes would silently affect nothing. The identity
// that can seed is the one identity nothing under test ever uses.
//
// Every run uses fresh uuids and a random label suffix, so tests that seed
// concurrently in the same container cannot see each other's fixtures — and
// could not act on them anyway, since each runs scoped to its own tenant.
func SeedTenants(tb testing.TB, superuser *pgxpool.Pool) Fixture {
	tb.Helper()

	run := uuid.NewString()[:8]

	fixture := Fixture{
		A:            seedTenant(tb, superuser, "alpha-"+run),
		B:            seedTenant(tb, superuser, "beta-"+run),
		SharedUserID: uuid.New(),
		SharedEmail:  "shared-" + run + "@example.com",
	}

	exec(tb, superuser, `INSERT INTO users (id, email, display_name) VALUES ($1, $2, $3)`,
		fixture.SharedUserID, fixture.SharedEmail, "Shared Contractor "+run)

	for _, t := range fixture.Tenants() {
		exec(tb, superuser, `INSERT INTO memberships (tenant_id, user_id, role) VALUES ($1, $2, 'member')`,
			t.TenantID, fixture.SharedUserID)
	}

	tb.Cleanup(func() {
		// Organizations cascade to memberships, projects, boards, columns and
		// cards. users is global, so it is outside that cascade and has to go
		// explicitly — the same asymmetry the schema is built around.
		for _, t := range fixture.Tenants() {
			exec(tb, superuser, `DELETE FROM organizations WHERE id = $1`, t.TenantID)
		}

		exec(tb, superuser, `DELETE FROM users WHERE id = ANY($1)`,
			[]uuid.UUID{fixture.SharedUserID, fixture.A.MemberID, fixture.B.MemberID})
	})

	return fixture
}

func seedTenant(tb testing.TB, superuser *pgxpool.Pool, label string) Tenant {
	tb.Helper()

	t := Tenant{
		Label:        label,
		TenantID:     uuid.New(),
		MemberID:     uuid.New(),
		MembershipID: uuid.New(),
		ProjectID:    uuid.New(),
		BoardID:      uuid.New(),
		ColumnID:     uuid.New(),
		CardID:       uuid.New(),
		MemberEmail:  label + "-member@example.com",
		CardTitle:    label + " card",
	}

	exec(tb, superuser, `INSERT INTO organizations (id, name, slug) VALUES ($1, $2, $3)`,
		t.TenantID, label+" org", label)
	exec(tb, superuser, `INSERT INTO users (id, email, display_name) VALUES ($1, $2, $3)`,
		t.MemberID, t.MemberEmail, label+" member")
	exec(tb, superuser, `INSERT INTO memberships (id, tenant_id, user_id, role) VALUES ($1, $2, $3, 'owner')`,
		t.MembershipID, t.TenantID, t.MemberID)
	exec(tb, superuser, `INSERT INTO projects (id, tenant_id, name) VALUES ($1, $2, $3)`,
		t.ProjectID, t.TenantID, label+" project")
	exec(tb, superuser, `INSERT INTO boards (id, tenant_id, project_id, name) VALUES ($1, $2, $3, $4)`,
		t.BoardID, t.TenantID, t.ProjectID, label+" board")
	exec(tb, superuser, `INSERT INTO columns (id, tenant_id, board_id, name, position) VALUES ($1, $2, $3, $4, 1)`,
		t.ColumnID, t.TenantID, t.BoardID, "Todo")
	exec(tb, superuser, `INSERT INTO cards (id, tenant_id, board_id, column_id, title, position) VALUES ($1, $2, $3, $4, $5, 1)`,
		t.CardID, t.TenantID, t.BoardID, t.ColumnID, t.CardTitle)

	return t
}

func exec(tb testing.TB, pool *pgxpool.Pool, sql string, args ...any) {
	tb.Helper()

	if _, err := pool.Exec(context.Background(), sql, args...); err != nil {
		tb.Fatalf("pgtest: seeding (%s): %v", sql, err)
	}
}
