# Every value here has a default or is set in terraform.tfvars. There is
# deliberately no variable in this configuration -- or in any module it calls --
# that accepts a secret, which is what makes committing terraform.tfvars safe:
# there is nothing sensitive it could hold. Credentials are generated by AWS
# (the RDS master password) or provisioned by #56, never passed in as input.

variable "aws_region" {
  description = "Region for every resource in this environment. Must match the `region` in the backend block in versions.tf."
  type        = string
}

variable "project" {
  description = "Project name; first component of every resource name."
  type        = string
  default     = "collabboard"
}

variable "environment" {
  description = "Environment name; second component of every resource name and the value of the `Environment` tag."
  type        = string
}

variable "vpc_cidr" {
  description = "CIDR block for this environment's VPC. Must not overlap another environment's."
  type        = string
}

variable "availability_zones" {
  description = "AZs to spread subnets across. Two AZs, named explicitly rather than discovered, so that a plan does not change because AWS reordered the AZ list."
  type        = list(string)
}

variable "nat_gateway_count" {
  description = "See modules/network/variables.tf. 0, 1 or 2. This is the largest single cost lever in the configuration."
  type        = number
}

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
}

variable "db_multi_az" {
  description = "Run an RDS standby in the second AZ. Doubles the instance cost."
  type        = bool
}

variable "db_allocated_storage" {
  description = "Initial RDS storage in GB."
  type        = number
  default     = 20
}

variable "db_max_allocated_storage" {
  description = "RDS storage autoscaling ceiling in GB. Exposed rather than left at a module default because autoscaling is one-way -- storage never scales back down, so this is the real upper bound on the storage line of the bill."
  type        = number
}

variable "db_backup_retention_days" {
  description = "RDS automated backup retention in days."
  type        = number
  default     = 7
}

variable "db_deletion_protection" {
  description = "Block deletion of the RDS instance."
  type        = bool
}

variable "db_skip_final_snapshot" {
  description = "Skip the final snapshot when the RDS instance is destroyed."
  type        = bool
}

variable "cache_node_type" {
  description = "ElastiCache node type."
  type        = string
}

variable "cache_node_count" {
  description = "Number of ElastiCache nodes. 1 means no automatic failover."
  type        = number
}

variable "attachments_force_destroy" {
  description = "Allow `terraform destroy` to delete the attachments bucket with objects still in it."
  type        = bool
  default     = false
}

variable "apply_immediately" {
  description = "Apply RDS and ElastiCache modifications at once instead of in the maintenance window."
  type        = bool
  default     = false
}
