// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_query.sql

package identitygen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
SELECT
    c.id::uuid AS id,
    c.email::text AS email,
    c.display_name::text AS display_name,
    c.created_at::timestamptz AS created_at
FROM public.identity_create_user($1, $2) AS c(id, email, display_name, created_at)
`

type CreateUserParams struct {
	Email       string
	DisplayName string
}

type CreateUserRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   time.Time
}

// Registration, and the "invited address has no account yet" branch of an
// invite. Permanently impossible from a tenant-scoped transaction rather than
// merely inconvenient there: the users WITH CHECK policy requires a membership
// joining the row to the current tenant, and that membership cannot exist
// before the user row it references does.
//
// A duplicate address surfaces as a unique violation (SQLSTATE 23505) from
// users_email_key rather than returning the existing row, because "already
// registered" and "here is the account you just made" are different answers.
// The invite flow asks ResolveUserIDByEmail first so it never has to ask this.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one

SELECT
    f.id::uuid AS id,
    f.email::text AS email,
    f.display_name::text AS display_name,
    f.created_at::timestamptz AS created_at
FROM public.identity_find_user_by_email($1) AS f(id, email, display_name, created_at)
`

type FindUserByEmailRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   time.Time
}

// The pre-tenant identity queries, and the complete list of them.
//
// These generate into a *different* package from query.sql
// (internal/store/internal/identitygen rather than .../gen), so the two doors
// hand out two interfaces with no methods in common. Code holding a
// store.IdentityQuerier cannot reach ListProjects, because the type has no such
// method: the narrowness is a compile error, not a convention.
//
// Every query below is one call to one SECURITY DEFINER function from migration
// 00004. None of them names a table, and none of them can: without a tenant the
// app role sees zero rows in users, memberships and organizations, and the only
// thing it holds EXECUTE on is those four functions. Adding a query here cannot
// widen the path on its own — a new capability needs a new function, a new
// grant and a migration, and that is the review point.
//
// Admission rule, applied to each of the four: the operation must be
// *impossible* through Store.WithTenant, not merely awkward there. Anything a
// tenant-scoped transaction could do belongs in query.sql instead.
//
// The casts and the column-definition lists are not decoration. sqlc reads
// CREATE FUNCTION from the migrations but does not expand a RETURNS TABLE into
// output columns, so `SELECT *` off one of these functions types as a single
// opaque `interface{}`. Naming the columns in the FROM clause and casting each
// one gives sqlc the types it cannot infer, and the result is a generated
// struct per row instead of an `any` every caller has to assert.
// Login. Pre-tenant because the input is an email: nothing has claimed an
// organization yet, so the RLS policy on users has nothing to key on.
//
// No row means no account with that address. #8 owns what a handler does about
// that; this shape neither forces nor forecloses a constant-time response, but
// it does mean the handler has to decide deliberately rather than inherit one.
func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT
    o.organization_id::uuid AS organization_id,
    o.name::text AS name,
    o.slug::text AS slug,
    o.role::text AS role,
    o.joined_at::timestamptz AS joined_at
FROM public.identity_list_user_organizations($1) AS o(organization_id, name, slug, role, joined_at)
`

type ListUserOrganizationsRow struct {
	OrganizationID uuid.UUID
	Name           string
	Slug           string
	Role           string
	JoinedAt       time.Time
}

// The organization switcher, immediately after login. Pre-tenant by
// definition — the question *is* "which tenants", so none can be current while
// it is asked, and the answer legitimately spans them.
//
// The function does not authorize. Callers must pass the id of the
// already-authenticated subject; passing one taken from a request body would
// turn this into a membership-disclosure endpoint.
func (q *Queries) ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationsRow{}
	for rows.Next() {
		var i ListUserOrganizationsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveUserIDByEmail = `-- name: ResolveUserIDByEmail :one
SELECT r.user_id::uuid AS user_id
FROM public.identity_resolve_user_id_by_email($1) AS r(user_id)
`

// Inviting a user who already has an account, possibly in an organization the
// inviting admin cannot see. Pre-tenant because looking outside the current
// tenant's visibility is the entire point.
//
// No row means the address is unregistered, which is the caller's signal to
// create the user instead. It returns the id and nothing else on purpose: the
// admin typed the address, so existence is all they learn, and nothing about
// the account's name or its other organizations is disclosed.
func (q *Queries) ResolveUserIDByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveUserIDByEmail, email)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
