// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_query.sql

package identitygen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPassword = `-- name: CreatePassword :one
SELECT c.user_id::uuid AS user_id
FROM public.identity_create_password(
    $1, $2, $3, $4, $5, $6, $7
) AS c(user_id)
`

type CreatePasswordParams struct {
	UserID      uuid.UUID
	Salt        []byte
	MemoryKib   int32
	Iterations  int32
	Parallelism int32
	KeyLength   int32
	Key         []byte
}

// Registration. Pre-tenant for the same reason CreateUser is: it runs in the
// same transaction, immediately after the user row it refers to, and before any
// organization exists to scope it to.
//
// INSERT with no ON CONFLICT, so calling it for a user who already has a
// credential raises unique_violation (23505) rather than silently overwriting
// one. Changing a password is a different feature and needs a different
// function, a different grant and its own review — this path cannot do it.
func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPassword,
		arg.UserID,
		arg.Salt,
		arg.MemoryKib,
		arg.Iterations,
		arg.Parallelism,
		arg.KeyLength,
		arg.Key,
	)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createUser = `-- name: CreateUser :one
SELECT
    c.id::uuid AS id,
    c.email::text AS email,
    c.display_name::text AS display_name,
    c.created_at::timestamptz AS created_at
FROM public.identity_create_user($1, $2) AS c(id, email, display_name, created_at)
`

type CreateUserParams struct {
	Email       string
	DisplayName string
}

type CreateUserRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   time.Time
}

// Registration, and the "invited address has no account yet" branch of an
// invite. Permanently impossible from a tenant-scoped transaction rather than
// merely inconvenient there: the users WITH CHECK policy requires a membership
// joining the row to the current tenant, and that membership cannot exist
// before the user row it references does.
//
// A duplicate address surfaces as a unique violation (SQLSTATE 23505) from
// users_email_key rather than returning the existing row, because "already
// registered" and "here is the account you just made" are different answers.
// The invite flow asks ResolveUserIDByEmail first so it never has to ask this.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one

SELECT
    f.id::uuid AS id,
    f.email::text AS email,
    f.display_name::text AS display_name,
    f.created_at::timestamptz AS created_at
FROM public.identity_find_user_by_email($1) AS f(id, email, display_name, created_at)
`

type FindUserByEmailRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   time.Time
}

// The pre-tenant identity queries, and the complete list of them.
//
// These generate into a *different* package from query.sql
// (internal/store/internal/identitygen rather than .../gen), so the two doors
// hand out two interfaces with no methods in common. Code holding a
// store.IdentityQuerier cannot reach ListProjects, because the type has no such
// method: the narrowness is a compile error, not a convention.
//
// Every query below is one call to one SECURITY DEFINER function from migration
// 00004. None of them names a table, and none of them can: without a tenant the
// app role sees zero rows in users, memberships and organizations, and the only
// thing it holds EXECUTE on is those four functions. Adding a query here cannot
// widen the path on its own — a new capability needs a new function, a new
// grant and a migration, and that is the review point.
//
// Admission rule, applied to each of the four: the operation must be
// *impossible* through Store.WithTenant, not merely awkward there. Anything a
// tenant-scoped transaction could do belongs in query.sql instead.
//
// The casts and the column-definition lists are not decoration. sqlc reads
// CREATE FUNCTION from the migrations but does not expand a RETURNS TABLE into
// output columns, so `SELECT *` off one of these functions types as a single
// opaque `interface{}`. Naming the columns in the FROM clause and casting each
// one gives sqlc the types it cannot infer, and the result is a generated
// struct per row instead of an `any` every caller has to assert.
// Login. Pre-tenant because the input is an email: nothing has claimed an
// organization yet, so the RLS policy on users has nothing to key on.
//
// No row means no account with that address. #8 owns what a handler does about
// that; this shape neither forces nor forecloses a constant-time response, but
// it does mean the handler has to decide deliberately rather than inherit one.
func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT
    o.organization_id::uuid AS organization_id,
    o.name::text AS name,
    o.slug::text AS slug,
    o.role::text AS role,
    o.joined_at::timestamptz AS joined_at
FROM public.identity_list_user_organizations($1) AS o(organization_id, name, slug, role, joined_at)
`

type ListUserOrganizationsRow struct {
	OrganizationID uuid.UUID
	Name           string
	Slug           string
	Role           string
	JoinedAt       time.Time
}

// The organization switcher, immediately after login. Pre-tenant by
// definition — the question *is* "which tenants", so none can be current while
// it is asked, and the answer legitimately spans them.
//
// The function does not authorize. Callers must pass the id of the
// already-authenticated subject; passing one taken from a request body would
// turn this into a membership-disclosure endpoint.
func (q *Queries) ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationsRow{}
	for rows.Next() {
		var i ListUserOrganizationsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const passwordParams = `-- name: PasswordParams :one

SELECT
    p.salt::bytea AS salt,
    p.memory_kib::integer AS memory_kib,
    p.iterations::integer AS iterations,
    p.parallelism::integer AS parallelism,
    p.key_length::integer AS key_length
FROM public.identity_password_params($1) AS p(salt, memory_kib, iterations, parallelism, key_length)
`

type PasswordParamsRow struct {
	Salt        []byte
	MemoryKib   int32
	Iterations  int32
	Parallelism int32
	KeyLength   int32
}

// The three queries below are the credential half of the pre-tenant path, added
// by issue #8. They travel the same Go door as the four above —
// Store.WithoutTenant — but their SECURITY DEFINER functions are owned by
// collabboard_credentials rather than collabboard_identity, and that role's
// privileges are strictly narrower: one table, in a schema (`auth`) the serving
// role holds no USAGE on, and nothing at all in `public`.
//
// So the identity door did not widen to accommodate a password. A second,
// smaller door was cut next to it. See migration 00005 and ADR 0003.
//
// Admission rule, same as above: each has to be *impossible* through
// Store.WithTenant. All three are, for the reason login is — they run before
// any organization has been claimed, and their subject is a global user rather
// than a tenant-scoped row.
// Step one of a login: the argon2id parameters needed to reproduce the
// derivation for this user.
//
// Returns no secret. A salt and a cost are public by construction — the code
// that needs them is the code that has to run the KDF — and the verifier is not
// in the function's return list at all. There is no query anywhere that returns
// it, which is the property ADR 0003 is about.
//
// No row means the user has no password set. internal/auth must not branch
// visibly on that: it derives stand-in parameters and does the full derivation
// anyway, so an unknown account costs what a known one does.
func (q *Queries) PasswordParams(ctx context.Context, userID uuid.UUID) (PasswordParamsRow, error) {
	row := q.db.QueryRow(ctx, passwordParams, userID)
	var i PasswordParamsRow
	err := row.Scan(
		&i.Salt,
		&i.MemoryKib,
		&i.Iterations,
		&i.Parallelism,
		&i.KeyLength,
	)
	return i, err
}

const resolveUserIDByEmail = `-- name: ResolveUserIDByEmail :one
SELECT r.user_id::uuid AS user_id
FROM public.identity_resolve_user_id_by_email($1) AS r(user_id)
`

// Inviting a user who already has an account, possibly in an organization the
// inviting admin cannot see. Pre-tenant because looking outside the current
// tenant's visibility is the entire point.
//
// No row means the address is unregistered, which is the caller's signal to
// create the user instead. It returns the id and nothing else on purpose: the
// admin typed the address, so existence is all they learn, and nothing about
// the account's name or its other organizations is disclosed.
func (q *Queries) ResolveUserIDByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, resolveUserIDByEmail, email)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const verifyPassword = `-- name: VerifyPassword :one
SELECT v.user_id::uuid AS user_id
FROM public.identity_verify_password($1, $2) AS v(user_id)
`

type VerifyPasswordParams struct {
	UserID uuid.UUID
	Key    []byte
}

// Step two of a login: the comparison, performed inside the database.
//
// The argument is the raw argon2id output, not the password and not the stored
// value. Postgres hashes it once more and compares against the stored verifier,
// so what is stored can never be replayed here.
//
// A uuid or no row. Never a boolean and never a reason: "no such user", "no
// password set" and "wrong password" are the same empty result, so no caller
// can leak which one happened by forwarding a status it was handed.
func (q *Queries) VerifyPassword(ctx context.Context, arg VerifyPasswordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, verifyPassword, arg.UserID, arg.Key)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
