// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identitygen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Registration, and the "invited address has no account yet" branch of an
	// invite. Permanently impossible from a tenant-scoped transaction rather than
	// merely inconvenient there: the users WITH CHECK policy requires a membership
	// joining the row to the current tenant, and that membership cannot exist
	// before the user row it references does.
	//
	// A duplicate address surfaces as a unique violation (SQLSTATE 23505) from
	// users_email_key rather than returning the existing row, because "already
	// registered" and "here is the account you just made" are different answers.
	// The invite flow asks ResolveUserIDByEmail first so it never has to ask this.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// The pre-tenant identity queries, and the complete list of them.
	//
	// These generate into a *different* package from query.sql
	// (internal/store/internal/identitygen rather than .../gen), so the two doors
	// hand out two interfaces with no methods in common. Code holding a
	// store.IdentityQuerier cannot reach ListProjects, because the type has no such
	// method: the narrowness is a compile error, not a convention.
	//
	// Every query below is one call to one SECURITY DEFINER function from migration
	// 00004. None of them names a table, and none of them can: without a tenant the
	// app role sees zero rows in users, memberships and organizations, and the only
	// thing it holds EXECUTE on is those four functions. Adding a query here cannot
	// widen the path on its own — a new capability needs a new function, a new
	// grant and a migration, and that is the review point.
	//
	// Admission rule, applied to each of the four: the operation must be
	// *impossible* through Store.WithTenant, not merely awkward there. Anything a
	// tenant-scoped transaction could do belongs in query.sql instead.
	//
	// The casts and the column-definition lists are not decoration. sqlc reads
	// CREATE FUNCTION from the migrations but does not expand a RETURNS TABLE into
	// output columns, so `SELECT *` off one of these functions types as a single
	// opaque `interface{}`. Naming the columns in the FROM clause and casting each
	// one gives sqlc the types it cannot infer, and the result is a generated
	// struct per row instead of an `any` every caller has to assert.
	// Login. Pre-tenant because the input is an email: nothing has claimed an
	// organization yet, so the RLS policy on users has nothing to key on.
	//
	// No row means no account with that address. #8 owns what a handler does about
	// that; this shape neither forces nor forecloses a constant-time response, but
	// it does mean the handler has to decide deliberately rather than inherit one.
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	// The organization switcher, immediately after login. Pre-tenant by
	// definition — the question *is* "which tenants", so none can be current while
	// it is asked, and the answer legitimately spans them.
	//
	// The function does not authorize. Callers must pass the id of the
	// already-authenticated subject; passing one taken from a request body would
	// turn this into a membership-disclosure endpoint.
	ListUserOrganizations(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationsRow, error)
	// Inviting a user who already has an account, possibly in an organization the
	// inviting admin cannot see. Pre-tenant because looking outside the current
	// tenant's visibility is the entire point.
	//
	// No row means the address is unregistered, which is the caller's signal to
	// create the user instead. It returns the id and nothing else on purpose: the
	// admin typed the address, so existence is all they learn, and nothing about
	// the account's name or its other organizations is disclosed.
	ResolveUserIDByEmail(ctx context.Context, email string) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
